
export const routes = {
    anygateForgotPassword: "https://www.anygate.vip/User/ChangePassword",
    adCenterLogin: "https://adc.wyav.tv?k=1",
    contactTelegram: "https://t.me/anthony93944",

    home: "/",
    signup: "/regiter",
    sendConfirmEmail: "/send-verification-email",
    confirmEmailSuccess: "/email-verification-successful",
    signin: "/login",
    forgotPassword: "/forgot-password",
    resetPassword: "/change-password",
    rankAll : "/rank/all",
    rankJapanKorea18 : "/rank/japankorea-18",
    rankWestern18 : "/rank/western-18",
    rankChina18 : "/rank/china-18",
    rankCartoon18 : "/rank/cartoon-18",
    mainList: "/list",
    list: "/list/svideo",
    listJapan: "/list/japan",
    listEuropean: "/list/european",
    listCartoon: "/list/cartoon",
    listDomestic: "/list/domestic",
    listGay: "/list/gay",
    watchHistory: "/user/watch-history",
    vipCenterIndex: "/vip-center/index",
    adCenter: "/ad-center/intro",
    adCenterStatus: "/ad-center/status",
    adCenterData: "/ad-center/data",
    adCenterDesign: "/ad-center/design",
    adCenterCalculator: "/ad-center/calculator",
    adCenterPayment: "/ad-center/payment",
    adCenterTerms: "/ad-center/terms",
    adCenterFaq: "/ad-center/faq",
    appDownload: "/app-download",
    search: "/search",
    vipCenter: "/vip-center/index/0",
    vipReCharge: "/vip-center/recharge",
    helpFaq: "/help/faq",
    helpVideo: "/help/video",
    helpFeedback: "/help/feedback",
    helpRecoveryPassword: "/help/recovery-password",
    helpTerm: "/help/terms",
    helpContactUs: "/help/contact-us",
    watch: "/watch",
    play: "/play",
    celebrities: "/celebrities",
    space: "/space",
    livestreamList: "https://www.yelive.tv",
    livestreamItem: "https://go.rmhfrtnd.com",
    helpTerm: "/help/terms",
    user: "/user",
    help: "/help",
    helpFeedback: "/help/feedback",
    helpContact: "/help/contact-us",
    helpFaq: "/help/faq",
    discovery: "/discovery",
    discoveryList: "/discovery/list",
    userIndex : "/user/index",
    userMyUpload: "user/my-upload",
    userMessagesChat: "/user/messages/chat?id=24ypEoyqCRsDthjnGYFjEA"
}